
package com.biblioteca.vista;
import com.biblioteca.gestor.Biblioteca;
import com.biblioteca.modelo.Libro;
import com.biblioteca.modelo.LibroTexto;
import com.biblioteca.modelo.LibroInvestigacion;
import com.biblioteca.excepciones.PersistenciaException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * Interfaz gráfica para la administración del inventario de libros.
 * Permite realizar operaciones CRUD (Crear, Leer, Eliminar) sobre los libros.
 * <p>
 * Esta vista maneja la lógica de presentación para crear diferentes tipos de libros
 * ({@link LibroTexto} o {@link LibroInvestigacion}) basándose en la selección del usuario,
 * demostrando el uso de polimorfismo desde la capa de presentación.
 * </p>
 * @author JeremyL, EnzoL
 * @version 1.0
 */
public class FrmGestionLibros extends javax.swing.JFrame {
    // Acceso al Singleton
    private final Biblioteca biblioteca = Biblioteca.getInstance();
    private DefaultTableModel modeloTablaLibros;


    /**
     * Inicializa la ventana, configura la tabla y carga los datos existentes.
     */
    public FrmGestionLibros() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabla(); // Inicializa la tabla al iniciar el formulario
        cmbTipoLibroActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        txtISBN = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        cmbTipoLibro = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        txtEdicion = new javax.swing.JTextField();
        txtFacultad = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        txtDOI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Libros");

        txtTitulo.setText("           ");
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtISBN.setText("         ");
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });

        txtAutor.setText("            ");
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        cmbTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Texto", "Investigación" }));
        cmbTipoLibro.setToolTipText("");
        cmbTipoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoLibroActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar/Agregar");
        btnGuardar.setOpaque(true);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtEdicion.setText("           ");
        txtEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdicionActionPerformed(evt);
            }
        });
        txtEdicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdicionKeyTyped(evt);
            }
        });

        txtFacultad.setText("           ");
        txtFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacultadActionPerformed(evt);
            }
        });

        txtTema.setText("          ");
        txtTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaActionPerformed(evt);
            }
        });

        txtDOI.setText("        ");
        txtDOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOIActionPerformed(evt);
            }
        });

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Titulo 5", "Titulo 6"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        btnEliminar.setText("Eliminar Seleccionado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("ISBN:");

        jLabel2.setText("Título:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Tema Principal:");

        jLabel5.setText("Edición:");

        jLabel6.setText("Facultad:");

        jLabel7.setText("DOI:");

        jButton1.setText("Salir al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Elija el tipo de Libro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(txtEdicion)
                                            .addComponent(txtDOI)
                                            .addComponent(txtFacultad)))))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(txtEdicion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(jButton1))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // MÉTODO QUE USA EL POLIMORFISMO Y LA HERENCIA para listar
    private void inicializarTabla() {
        // Define las columnas para la JTable
        modeloTablaLibros = new DefaultTableModel(
            new Object[]{"ISBN", "Título", "Tipo", "Disponible", "Autor"}, 0
        );
        tblLibros.setModel(modeloTablaLibros);
        cargarDatosTabla();
    }
    /**
     * Recorre la lista de libros del sistema y los muestra en la tabla.
     * Utiliza `instanceof` para determinar el tipo de libro y mostrarlo correctamente.
     */
    private void cargarDatosTabla() {
        modeloTablaLibros.setRowCount(0); // Limpiar filas
        
        for (Libro libro : biblioteca.gestorLibros.listarTodo()) {
            
            // Determina el tipo real del objeto (DEMOSTRACIÓN DE POLIMORFISMO en la vista)
            String tipo = (libro instanceof LibroTexto) ? "Texto" : "Investigación";
            
            modeloTablaLibros.addRow(new Object[]{
                libro.getISBN(), 
                libro.getTitulo(), 
                tipo,
                libro.isDisponible() ? "Sí" : "No",
                libro.getAutor()
            });
        }
    }
    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void cmbTipoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoLibroActionPerformed
        String seleccion = cmbTipoLibro.getSelectedItem().toString();
        boolean esTexto = seleccion.equals("Texto");

        // 2. Controlar visibilidad de etiquetas y campos
        // Campos exclusivos de TEXTO
        txtEdicion.setVisible(esTexto);
        txtFacultad.setVisible(esTexto);
        jLabel5.setVisible(esTexto); // Etiqueta "Edición"
        jLabel6.setVisible(esTexto); // Etiqueta "Facultad"

        // Campos exclusivos de INVESTIGACIÓN
        txtTema.setVisible(!esTexto);
        txtDOI.setVisible(!esTexto);
        jLabel4.setVisible(!esTexto); // Etiqueta "Tema Principal"
        jLabel7.setVisible(!esTexto); // Etiqueta "DOI"

        // (Opcional) Revalidar el panel para que se ajuste visualmente
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_cmbTipoLibroActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void txtEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdicionActionPerformed

    private void txtFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacultadActionPerformed

    private void txtTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaActionPerformed

    private void txtDOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOIActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblLibros.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un libro de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String isbnEliminar = modeloTablaLibros.getValueAt(filaSeleccionada, 0).toString();

        try {
            // LLAMADA AL BACKEND: Buscar por ISBN usando el Predicate (Genéricos)
            Libro libroAEliminar = biblioteca.gestorLibros.buscarPorIdentificador(l -> l.getISBN().equals(isbnEliminar));
            
            if (libroAEliminar != null) {
                if (!libroAEliminar.isDisponible()) {
                    JOptionPane.showMessageDialog(this, "No se puede eliminar: el libro está actualmente prestado.", "Restricción", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                biblioteca.gestorLibros.eliminar(libroAEliminar); 
                cargarDatosTabla();
                JOptionPane.showMessageDialog(this, "Libro " + isbnEliminar + " eliminado y persistido.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                 JOptionPane.showMessageDialog(this, "Libro no encontrado en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // 1. Crear y mostrar el menú principal
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);

        // 2. Ocultar el formulario actual
        this.dispose(); // Cierra esta ventana y libera recursos
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String isbn = txtISBN.getText().trim();
        String titulo = txtTitulo.getText().trim();
        String autor = txtAutor.getText().trim();
        String tipo = cmbTipoLibro.getSelectedItem().toString(); 
        Libro nuevoLibro = null;
        
        try {
            if (isbn.isEmpty() || titulo.isEmpty() || autor.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Campos principales (ISBN, Título, Autor) incompletos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                 return;
            }
            
            // Creación polimórfica del objeto basada en la selección
            if (tipo.equals("Texto")) {
                int edicion = Integer.parseInt(txtEdicion.getText());
                nuevoLibro = new LibroTexto(isbn, titulo, autor, txtFacultad.getText(), edicion);
            } else if (tipo.equals("Investigación")) {
                nuevoLibro = new LibroInvestigacion(isbn, titulo, autor, txtTema.getText(), txtDOI.getText());
            }

            if (nuevoLibro != null) {
                // LLAMADA AL BACKEND: Usa Genéricos y Persistencia
                biblioteca.gestorLibros.agregar(nuevoLibro); 
                cargarDatosTabla(); // Actualiza la JTable
                JOptionPane.showMessageDialog(this, "Libro " + titulo + " guardado y persistido.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                // Limpiar campos
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La edición debe ser un número válido.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error crítico de Persistencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // 1. Crear y mostrar el menú principal
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);

        // 2. Ocultar el formulario actual
        this.dispose(); // Cierra esta ventana y libera recursos
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEdicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdicionKeyTyped
        char c = evt.getKeyChar();
        // Si no es dígito y no es la tecla de borrar, lo bloqueamos
        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Ignora el evento (no escribe la letra)
            getToolkit().beep(); // Sonido de alerta opcional
        }
    }//GEN-LAST:event_txtEdicionKeyTyped
    private void limpiarCampos() {
    txtISBN.setText("");
    txtTitulo.setText("");
    txtAutor.setText("");
    txtFacultad.setText("");
    txtEdicion.setText("");
    txtTema.setText("");
    txtDOI.setText("");
    cmbTipoLibro.setSelectedIndex(0); // Selecciona la primera opción
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTipoLibro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtDOI;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtFacultad;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
