
package com.biblioteca.vista;
import com.biblioteca.gestor.Biblioteca;
import com.biblioteca.modelo.Estudiante;
import com.biblioteca.excepciones.PersistenciaException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * Interfaz gráfica para el registro y mantenimiento de estudiantes.
 * Permite agregar nuevos estudiantes al sistema y eliminarlos, validando
 * previamente que no tengan préstamos pendientes.
 * <p>
 * Muestra en tiempo real el estado de los préstamos de cada estudiante
 * (cantidad de libros prestados vs límite permitido).
 * </p>
 * @author JeremyL, EnzoL
 * @version 1.0
 */
public class FrmGestionEstudiantes extends javax.swing.JFrame {
    
    private final Biblioteca biblioteca = Biblioteca.getInstance();
    private DefaultTableModel modeloTablaEstudiantes;
    
    /**
     * Crea la ventana de gestión de estudiantes e inicializa la tabla de datos.
     */
    public FrmGestionEstudiantes() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabla();
    }
    private void inicializarTabla() {
        modeloTablaEstudiantes = new DefaultTableModel(
            new Object[]{"Código", "Nombre", "Carrera", "Préstamos"}, 0
        );
        tblEstudiantes.setModel(modeloTablaEstudiantes);
        cargarDatosTabla();
    }
    // Método que carga los datos de los estudiantes desde el gestor a la tabla
    private void cargarDatosTabla() {
        modeloTablaEstudiantes.setRowCount(0); // Limpiar filas

        // Uso del Gestor Genérico para listar Estudiantes
        for (Estudiante estudiante : biblioteca.gestorEstudiantes.listarTodo()) {
            modeloTablaEstudiantes.addRow(new Object[]{
                estudiante.getCodigo(), 
                estudiante.getNombre(), 
                estudiante.getCarrera(),
                // Muestra el número de libros prestados, usando el límite del modelo Estudiante
                estudiante.getLibrosPrestados().size() + " / " + estudiante.getMaxLibros() 
            });
        }
    }
    
    // Método de utilidad para limpiar la interfaz de usuario
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtCarrera.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtCarrera = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Estudiantes");

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Carrera:");

        jLabel3.setText("Código:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEstudiantes);

        jButton4.setText("Salir al Menú");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtCarrera))
                                .addGap(146, 146, 146)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String carrera = txtCarrera.getText().trim();

        try {
            if (codigo.isEmpty() || nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar el Código y el Nombre del estudiante.", 
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // 1. Verificar si ya existe para evitar duplicados (Uso de Predicate)
            Estudiante estudianteExistente = biblioteca.gestorEstudiantes.buscarPorIdentificador(e -> e.getCodigo().equals(codigo));
            
            if (estudianteExistente != null) {
                 JOptionPane.showMessageDialog(this, "El estudiante con código " + codigo + " ya existe.", 
                         "Error de Duplicado", JOptionPane.ERROR_MESSAGE);
                 return;
            }

            // 2. Crear el nuevo objeto Estudiante
            Estudiante nuevoEstudiante = new Estudiante(codigo, nombre, carrera);
            
            // 3. LLAMADA AL BACKEND: Agregar y Persistir 
            biblioteca.gestorEstudiantes.agregar(nuevoEstudiante);
            
            cargarDatosTabla(); 
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Estudiante " + nombre + " guardado y persistido.", 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblEstudiantes.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un estudiante de la tabla para eliminar.", 
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // El código (identificador) está en la primera columna (índice 0)
        String codigoEliminar = modeloTablaEstudiantes.getValueAt(filaSeleccionada, 0).toString();
        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de eliminar al estudiante con código " + codigoEliminar + "?",
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                // LLAMADA AL BACKEND: Buscar por Código
                Estudiante estudianteAEliminar = biblioteca.gestorEstudiantes.buscarPorIdentificador(e -> e.getCodigo().equals(codigoEliminar));

                if (estudianteAEliminar != null) {
                    // Validación de integridad: No se puede eliminar si tiene libros prestados
                    if (!estudianteAEliminar.getLibrosPrestados().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No se puede eliminar: el estudiante tiene préstamos activos.", 
                                "Restricción de Integridad", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    // Eliminar y persistir
                    biblioteca.gestorEstudiantes.eliminar(estudianteAEliminar); 
                    cargarDatosTabla();
                    JOptionPane.showMessageDialog(this, "Estudiante " + codigoEliminar + " eliminado y persistido.", 
                            "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Estudiante no encontrado en el sistema.", 
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (PersistenciaException e) {
                JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        menu.setVisible(true);

        // 2. Ocultar el formulario actual
        this.dispose(); // Cierra esta ventana y libera recursos
    }//GEN-LAST:event_jButton4ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
