
package com.biblioteca.vista;
import com.biblioteca.gestor.Biblioteca;
import com.biblioteca.modelo.Estudiante;
import com.biblioteca.excepciones.PersistenciaException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FrmGestionEstudiantes extends javax.swing.JFrame {
    
    private final Biblioteca biblioteca = Biblioteca.getInstance();
    private DefaultTableModel modeloTablaEstudiantes;
    
  
    public FrmGestionEstudiantes() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabla();
    }
    private void inicializarTabla() {
        modeloTablaEstudiantes = new DefaultTableModel(
            new Object[]{"Código", "Nombre", "Carrera", "Préstamos"}, 0
        );
        tblEstudiantes.setModel(modeloTablaEstudiantes);
        cargarDatosTabla();
    }
    // Método que carga los datos de los estudiantes desde el gestor a la tabla
    private void cargarDatosTabla() {
        modeloTablaEstudiantes.setRowCount(0); // Limpiar filas

        // Uso del Gestor Genérico para listar Estudiantes
        for (Estudiante estudiante : biblioteca.gestorEstudiantes.listarTodo()) {
            modeloTablaEstudiantes.addRow(new Object[]{
                estudiante.getCodigo(), 
                estudiante.getNombre(), 
                estudiante.getCarrera(),
                // Muestra el número de libros prestados, usando el límite del modelo Estudiante
                estudiante.getLibrosPrestados().size() + " / " + estudiante.getMaxLibros() 
            });
        }
    }
    
    // Método de utilidad para limpiar la interfaz de usuario
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtCarrera.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtCarrera = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Carrera:");

        jLabel3.setText("Código:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtCarrera.setText("                 ");

        txtNombre.setText("                 ");

        txtCodigo.setText("                     ");

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(btnGuardar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombre)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo)
                                .addComponent(txtCarrera)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnGuardar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String carrera = txtCarrera.getText().trim();

        try {
            if (codigo.isEmpty() || nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar el Código y el Nombre del estudiante.", 
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // 1. Verificar si ya existe para evitar duplicados (Uso de Predicate)
            Estudiante estudianteExistente = biblioteca.gestorEstudiantes.buscarPorIdentificador(e -> e.getCodigo().equals(codigo));
            
            if (estudianteExistente != null) {
                 JOptionPane.showMessageDialog(this, "El estudiante con código " + codigo + " ya existe.", 
                         "Error de Duplicado", JOptionPane.ERROR_MESSAGE);
                 return;
            }

            // 2. Crear el nuevo objeto Estudiante
            Estudiante nuevoEstudiante = new Estudiante(codigo, nombre, carrera);
            
            // 3. LLAMADA AL BACKEND: Agregar y Persistir 
            biblioteca.gestorEstudiantes.agregar(nuevoEstudiante);
            
            cargarDatosTabla(); 
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Estudiante " + nombre + " guardado y persistido.", 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblEstudiantes.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un estudiante de la tabla para eliminar.", 
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // El código (identificador) está en la primera columna (índice 0)
        String codigoEliminar = modeloTablaEstudiantes.getValueAt(filaSeleccionada, 0).toString();

        try {
            // LLAMADA AL BACKEND: Buscar por Código
            Estudiante estudianteAEliminar = biblioteca.gestorEstudiantes.buscarPorIdentificador(e -> e.getCodigo().equals(codigoEliminar));
            
            if (estudianteAEliminar != null) {
                // Validación de integridad: No se puede eliminar si tiene libros prestados
                if (!estudianteAEliminar.getLibrosPrestados().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No se puede eliminar: el estudiante tiene préstamos activos.", 
                            "Restricción de Integridad", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                // Eliminar y persistir
                biblioteca.gestorEstudiantes.eliminar(estudianteAEliminar); 
                cargarDatosTabla();
                JOptionPane.showMessageDialog(this, "Estudiante " + codigoEliminar + " eliminado y persistido.", 
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Estudiante no encontrado en el sistema.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
