
package com.biblioteca.vista;
import com.biblioteca.gestor.Biblioteca;
import com.biblioteca.excepciones.LimitePrestamosExcedidoException;
import com.biblioteca.excepciones.PersistenciaException;
import com.biblioteca.excepciones.RecursoNoEncontradoException;
import com.biblioteca.modelo.Estudiante;
import com.biblioteca.modelo.Libro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmPrestamosDevolucion extends javax.swing.JFrame {
    
    private final Biblioteca biblioteca = Biblioteca.getInstance();

    
    public FrmPrestamosDevolucion() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabla();
    }
    private void inicializarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ISBN", "Título", "Tipo"}, 0
        );
        tblPrestamosActivos.setModel(modelo);
    }
    // Método para cargar los libros que tiene prestados un estudiante
    private void cargarPrestamosActivos(String codigoEstudiante) {
        DefaultTableModel modelo = (DefaultTableModel) tblPrestamosActivos.getModel();
        modelo.setRowCount(0); // Limpiar filas

        try {
            // Se busca al estudiante usando el gestor genérico (Predicate)
            Estudiante estudiante = biblioteca.gestorEstudiantes.buscarPorIdentificador(e -> e.getCodigo().equals(codigoEstudiante));
            
            if (estudiante == null) {
                JOptionPane.showMessageDialog(this, "Estudiante no encontrado.", 
                        "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Llenar la tabla con los libros prestados
            for (Libro libro : estudiante.getLibrosPrestados()) {
                String tipo = (libro instanceof com.biblioteca.modelo.LibroTexto) ? "Texto" : "Investigación";
                modelo.addRow(new Object[]{
                    libro.getISBN(), 
                    libro.getTitulo(), 
                    tipo
                });
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al cargar préstamos: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtI = new javax.swing.JLabel();
        txtCod = new javax.swing.JLabel();
        txtCodigoEstudiante = new javax.swing.JTextField();
        txtISBNPrestamo = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCod1 = new javax.swing.JLabel();
        txtISBNDevolucion = new javax.swing.JTextField();
        txtCodigoDevolucion = new javax.swing.JTextField();
        txtI1 = new javax.swing.JLabel();
        btnBuscarPrestamos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamosActivos = new javax.swing.JTable();
        btnDevolver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DEVOLUCIÓN");
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 160));

        txtI.setText("ISBN del Libro:");
        txtI.setPreferredSize(new java.awt.Dimension(130, 160));

        txtCod.setText("Código alumno:");
        txtCod.setPreferredSize(new java.awt.Dimension(130, 160));

        txtCodigoEstudiante.setText("Inserte...");

        txtISBNPrestamo.setText("Inserte...");

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        jLabel2.setText("        PRÉSTAMOS");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 160));

        txtCod1.setText("Código alumno:");
        txtCod1.setPreferredSize(new java.awt.Dimension(130, 160));

        txtISBNDevolucion.setText("Inserte...");

        txtCodigoDevolucion.setText("Inserte...");

        txtI1.setText("ISBN del Libro:");
        txtI1.setPreferredSize(new java.awt.Dimension(130, 160));

        btnBuscarPrestamos.setText("Buscar Préstamos");
        btnBuscarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamosActionPerformed(evt);
            }
        });

        tblPrestamosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamosActivos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tblPrestamosActivosComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamosActivos);

        btnDevolver1.setText("Devolver");
        btnDevolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtISBNPrestamo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBNDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnBuscarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(btnDevolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(252, 252, 252)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtISBNPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDevolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBNDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(654, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
       String codEstudiante = txtCodigoEstudiante.getText().trim();
        String isbn = txtISBNPrestamo.getText().trim();

        if (codEstudiante.isEmpty() || isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Código de Estudiante y el ISBN.", 
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // LLAMADA AL SINGLETON para la lógica de negocio central
            biblioteca.realizarPrestamo(codEstudiante, isbn);
            
            // Si tiene éxito, recargamos la tabla del estudiante
            cargarPrestamosActivos(codEstudiante);
            
            // Limpieza de campos
            txtISBNPrestamo.setText("");

            JOptionPane.showMessageDialog(this, 
                    "Préstamo realizado exitosamente.\nEstudiante: " + codEstudiante + " | Libro: " + isbn,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (LimitePrestamosExcedidoException e) {
            // Captura de EXCEPCIÓN PERSONALIZADA: Límite de POO
            JOptionPane.showMessageDialog(this, "Error de Préstamo: " + e.getMessage(), 
                    "Límite Excedido", JOptionPane.ERROR_MESSAGE);
        } catch (RecursoNoEncontradoException e) {
            // Captura de EXCEPCIÓN PERSONALIZADA: Recurso no existe
            JOptionPane.showMessageDialog(this, "Error de Búsqueda: " + e.getMessage(), 
                    "Recurso No Encontrado", JOptionPane.WARNING_MESSAGE);
        } catch (PersistenciaException e) {
            // Captura de EXCEPCIÓN POR ARCHIVOS: Error de Serialización
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                    "Error Grave", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnBuscarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamosActionPerformed
        String codEstudiante = txtCodigoDevolucion.getText().trim(); // Usa el campo de devolución
        if (!codEstudiante.isEmpty()) {
             cargarPrestamosActivos(codEstudiante);
        } else {
             JOptionPane.showMessageDialog(this, "Ingrese el Código del Estudiante para buscar préstamos activos.", 
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarPrestamosActionPerformed

    private void tblPrestamosActivosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblPrestamosActivosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPrestamosActivosComponentAdded

    private void btnDevolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolver1ActionPerformed
        String codEstudiante = txtCodigoDevolucion.getText().trim();
        String isbn = txtISBNDevolucion.getText().trim();

        if (codEstudiante.isEmpty() || isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Código de Estudiante y el ISBN.", 
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // LLAMADA AL SINGLETON para la lógica de negocio central
            biblioteca.realizarDevolucion(codEstudiante, isbn);
            
            // Si tiene éxito, recargamos la tabla del estudiante
            cargarPrestamosActivos(codEstudiante); 
            
            // Limpieza de campos
            txtISBNDevolucion.setText("");
            
            JOptionPane.showMessageDialog(this, 
                    "Devolución realizada exitosamente.\nEstudiante: " + codEstudiante + " | Libro: " + isbn,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (RecursoNoEncontradoException e) {
            // Captura de EXCEPCIÓN PERSONALIZADA: El libro no estaba prestado o el estudiante no existe
            JOptionPane.showMessageDialog(this, "Error de Devolución: " + e.getMessage(), 
                    "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        } catch (PersistenciaException e) {
             // Captura de EXCEPCIÓN POR ARCHIVOS: Error de Serialización
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                    "Error Grave", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDevolver1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamos;
    private javax.swing.JButton btnDevolver1;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamosActivos;
    private javax.swing.JLabel txtCod;
    private javax.swing.JLabel txtCod1;
    private javax.swing.JTextField txtCodigoDevolucion;
    private javax.swing.JTextField txtCodigoEstudiante;
    private javax.swing.JLabel txtI;
    private javax.swing.JLabel txtI1;
    private javax.swing.JTextField txtISBNDevolucion;
    private javax.swing.JTextField txtISBNPrestamo;
    // End of variables declaration//GEN-END:variables
}
