
package com.biblioteca.vista;
import com.biblioteca.gestor.Biblioteca;
import com.biblioteca.excepciones.LimitePrestamosExcedidoException;
import com.biblioteca.excepciones.PersistenciaException;
import com.biblioteca.excepciones.RecursoNoEncontradoException;
import com.biblioteca.modelo.Estudiante;
import com.biblioteca.modelo.Libro;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * Interfaz para gestionar el flujo de préstamos y devoluciones.
 * Actúa como intermediario entre el usuario y la lógica transaccional de la clase {@link Biblioteca}.
 * <p>
 * Maneja las excepciones de negocio (como {@link LimitePrestamosExcedidoException} o
 * {@link RecursoNoEncontradoException}) y muestra mensajes de error amigables al usuario.
 * </p>
 * @author JeremyL, EnzoL
 * @version 1.0
 */
public class FrmPrestamosDevolucion extends javax.swing.JFrame {
    
    private final Biblioteca biblioteca = Biblioteca.getInstance();

    /**
     * Inicializa los componentes de la interfaz de préstamos.
     */
    public FrmPrestamosDevolucion() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarTabla();
    }
    private void inicializarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ISBN", "Título", "Tipo"}, 0
        );
        tblPrestamosActivos.setModel(modelo);
    }
    /**
     * Busca y muestra en la tabla los libros que un estudiante específico tiene prestados actualmente.
     * @param codigoEstudiante El código del estudiante a consultar.
     */
    private void cargarPrestamosActivos(String codigoEstudiante) {
        DefaultTableModel modelo = (DefaultTableModel) tblPrestamosActivos.getModel();
        modelo.setRowCount(0); // Limpiar filas

        try {
            // Se busca al estudiante usando el gestor genérico (Predicate)
            Estudiante estudiante = biblioteca.gestorEstudiantes.buscarPorIdentificador(e -> e.getCodigo().equals(codigoEstudiante));
            
            if (estudiante == null) {
                JOptionPane.showMessageDialog(this, "Estudiante no encontrado.", 
                        "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Llenar la tabla con los libros prestados
            for (Libro libro : estudiante.getLibrosPrestados()) {
                String tipo = (libro instanceof com.biblioteca.modelo.LibroTexto) ? "Texto" : "Investigación";
                modelo.addRow(new Object[]{
                    libro.getISBN(), 
                    libro.getTitulo(), 
                    tipo
                });
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al cargar préstamos: " + e.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamosActivos = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtCod = new javax.swing.JLabel();
        txtCodigoEstudiante = new javax.swing.JTextField();
        txtI = new javax.swing.JLabel();
        txtISBNPrestamo = new javax.swing.JTextField();
        btnPrestar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCod1 = new javax.swing.JLabel();
        txtCodigoDevolucion = new javax.swing.JTextField();
        txtI1 = new javax.swing.JLabel();
        txtISBNDevolucion = new javax.swing.JTextField();
        btnDevolver1 = new javax.swing.JButton();
        btnBuscarPrestamos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prestamos y Devolucion");

        tblPrestamosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamosActivos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tblPrestamosActivosComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamosActivos);

        jTabbedPane1.setName("Realizar Prestamo"); // NOI18N

        txtCod.setText("Código alumno:");
        txtCod.setPreferredSize(new java.awt.Dimension(130, 160));

        txtCodigoEstudiante.setText("Inserte...");

        txtI.setText("ISBN del Libro:");
        txtI.setPreferredSize(new java.awt.Dimension(130, 160));

        txtISBNPrestamo.setText("Inserte...");

        btnPrestar.setText("Prestar");
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtISBNPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(txtCodigoEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtISBNPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Reallziar Prestamo", jPanel1);

        txtCod1.setText("Código alumno:");
        txtCod1.setPreferredSize(new java.awt.Dimension(130, 160));

        txtCodigoDevolucion.setText("Inserte...");

        txtI1.setText("ISBN del Libro:");
        txtI1.setPreferredSize(new java.awt.Dimension(130, 160));

        txtISBNDevolucion.setText("Inserte...");

        btnDevolver1.setText("Devolver");
        btnDevolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolver1ActionPerformed(evt);
            }
        });

        btnBuscarPrestamos.setText("Buscar Préstamos");
        btnBuscarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPrestamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoDevolucion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtISBNDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolver1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPrestamos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtI1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtISBNDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Devoluciones", jPanel2);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir al Menú");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(264, 264, 264)
                    .addComponent(btnSalir)
                    .addContainerGap(264, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(btnSalir)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
       String codEstudiante = txtCodigoEstudiante.getText().trim();
        String isbn = txtISBNPrestamo.getText().trim();

        if (codEstudiante.isEmpty() || isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Código de Estudiante y el ISBN.", 
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // LLAMADA AL SINGLETON para la lógica de negocio central
            biblioteca.realizarPrestamo(codEstudiante, isbn);
            
            // Si tiene éxito, recargamos la tabla del estudiante
            cargarPrestamosActivos(codEstudiante);
            
            // Limpieza de campos
            txtISBNPrestamo.setText("");

            JOptionPane.showMessageDialog(this, 
                    "Préstamo realizado exitosamente.\nEstudiante: " + codEstudiante + " | Libro: " + isbn,
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (LimitePrestamosExcedidoException e) {
            // Captura de EXCEPCIÓN PERSONALIZADA: Límite de POO
            JOptionPane.showMessageDialog(this, "Error de Préstamo: " + e.getMessage(), 
                    "Límite Excedido", JOptionPane.ERROR_MESSAGE);
        } catch (RecursoNoEncontradoException e) {
            // Captura de EXCEPCIÓN PERSONALIZADA: Recurso no existe
            JOptionPane.showMessageDialog(this, "Error de Búsqueda: " + e.getMessage(), 
                    "Recurso No Encontrado", JOptionPane.WARNING_MESSAGE);
        } catch (PersistenciaException e) {
            // Captura de EXCEPCIÓN POR ARCHIVOS: Error de Serialización
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(), 
                    "Error Grave", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void tblPrestamosActivosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tblPrestamosActivosComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPrestamosActivosComponentAdded

    private void btnBuscarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamosActionPerformed
        String codEstudiante = txtCodigoDevolucion.getText().trim(); // Usa el campo de devolución
        if (!codEstudiante.isEmpty()) {
            cargarPrestamosActivos(codEstudiante);
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese el Código del Estudiante para buscar préstamos activos.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarPrestamosActionPerformed

    private void btnDevolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolver1ActionPerformed
        String codEstudiante = txtCodigoDevolucion.getText().trim();
        String isbn = txtISBNDevolucion.getText().trim();

        if (codEstudiante.isEmpty() || isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Código de Estudiante y el ISBN.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // LLAMADA AL SINGLETON para la lógica de negocio central
            biblioteca.realizarDevolucion(codEstudiante, isbn);

            // Si tiene éxito, recargamos la tabla del estudiante
            cargarPrestamosActivos(codEstudiante);

            // Limpieza de campos
            txtISBNDevolucion.setText("");

            JOptionPane.showMessageDialog(this,
                "Devolución realizada exitosamente.\nEstudiante: " + codEstudiante + " | Libro: " + isbn,
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (RecursoNoEncontradoException e) {
            // Captura de EXCEPCIÓN PERSONALIZADA: El libro no estaba prestado o el estudiante no existe
            JOptionPane.showMessageDialog(this, "Error de Devolución: " + e.getMessage(),
                "Error de Búsqueda", JOptionPane.WARNING_MESSAGE);
        } catch (PersistenciaException e) {
            // Captura de EXCEPCIÓN POR ARCHIVOS: Error de Serialización
            JOptionPane.showMessageDialog(this, "Error de Persistencia: " + e.getMessage(),
                "Error Grave", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDevolver1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Llama al Singleton para guardar todos los datos antes de salir
        try {
            // Llama al método de persistencia de la Fachada (Biblioteca)
            biblioteca.guardarTodo();
            JOptionPane.showMessageDialog(this, "Datos guardados. Saliendo del sistema.", "Cierre Exitoso", JOptionPane.INFORMATION_MESSAGE);
        } catch (PersistenciaException e) {
            // Manejo de la Excepción Personalizada
            JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        } finally {
            System.exit(0); // Cierra la aplicación Java de forma segura
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalir1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamos;
    private javax.swing.JButton btnDevolver1;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPrestamosActivos;
    private javax.swing.JLabel txtCod;
    private javax.swing.JLabel txtCod1;
    private javax.swing.JTextField txtCodigoDevolucion;
    private javax.swing.JTextField txtCodigoEstudiante;
    private javax.swing.JLabel txtI;
    private javax.swing.JLabel txtI1;
    private javax.swing.JTextField txtISBNDevolucion;
    private javax.swing.JTextField txtISBNPrestamo;
    // End of variables declaration//GEN-END:variables
}
